---
apiVersion: v1
kind: Template
labels:
  app: tang
  template: tang
metadata:
  name: tang
  annotations:
    description: API backend for tang server deployment in console.redhat.com

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: tang-server
      labels:
        app: tang-server
        service: tang-server
    spec:
      envName: ${ENV_NAME}
      featureFlags: false
      deployments:
        - name: deployment
          replicas: 1
          webServices:
            public:
              enabled: true
              apiPath: dee-hms
          podSpec:
            image: ${IMG}:${IMG_TAG}
            command:
              - /usr/bin/tangd-entrypoint
            env:
              - name: PORT
                value: ${ADV_INTERNAL_PORT}
            livenessProbe:
              exec:
                command:
                - /usr/bin/tangd-health-check
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 15
            readinessProbe:
              exec:
                command:
                - /usr/bin/tangd-health-check
              initialDelaySeconds: 27
              periodSeconds: 10
              timeoutSeconds: 5
            volumes:
              - persistentVolumeClaim:
                  claimName: tangserver-pvc
                name: tangserver-pvc
            volumeMounts:
              - mountPath: /var/db
                name: tangserver-pvc

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: tangserver-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

# possible application ENV variables are in config/api.env.example
parameters:
  - description: ClowdEnv Name
    name: ENV_NAME
    value: "Tang"
  - description: Image tag
    name: IMG_TAG
    value: "dee-hms-socat"
  - description: Image name
    name: IMG
    value: quay.io/sec-eng-special/tang
  - description: Advertising internal port
    name: ADV_INTERNAL_PORT
    value: "8000"
